#!/bin/bash
set -e

./build
docker push jerrington/docli:latest
ssh j <<EOF
set -e
cd /site/nether-portal
docker-compose down &
docker pull jerrington/docli:latest &
wait
docker-compose up -d

cd /site/homescreen
docker-compose down
sleep 1
docker-compose up -d
EOF
