services:
  docli:
    image: jerrington/docli:latest
    env_file: .env # configure BOT_TOKEN in here
    environment:
      VAULT_DIR: /vault
      TODO_PATH: Todo.md
      HABITS_PATH: Habits.md
      TASK_TAG: "#task"
      CHANNEL_NAME: jake-cli
      GIT_NAME: "Discord Obsidian CLI"
      # GIT_EMAIL: # Configure here or in .env
      # GIT_UPSTREAM: # Configure here or in .env
    volumes:
      - vault:/vault
      - $HOME/.ssh/id_ed25519:/root/ssh/id_ed25519:ro

volumes:
  vault:
